# Generated by Django 3.2.7 on 2021-11-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('pswd', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('noof_current_books', models.IntegerField(blank=True, null=True)),
                ('n_read', models.IntegerField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
