# Generated by Django 3.2.7 on 2021-11-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('publi_date', models.DateField(blank=True, null=True)),
                ('n_copies', models.IntegerField(blank=True, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('n_read', models.IntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/')),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
    ]
